name: Build a Docker Image and Push it to Docker Hub

on:
  push:
    tags:
      - "v*"

env:
  DOCKER_USERNAME: anbiozz
  IMAGE_NAME: gpx2json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: |
            "${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}",
            "${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            "${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}",
            "${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
