name: Security check

on: push

env:
  FAKE_DOCKER_USERNAME: mydockerhubusername
  FAKE_IMAGE_NAME: my-image-name
  FAKE_IMAGE_TAG: current

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: docker://hadolint/hadolint:latest
        with:
          args: hadolint Dockerfile

  sca-python:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/python-3.10@master
        with:
          args: --sarif-file-output=snyk_python.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload Snyk scan Python result to GitHub Code Scanning
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "snyk_python.sarif"

  sca-image:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: "${{ env.FAKE_DOCKER_USERNAME }}/${{ env.FAKE_IMAGE_NAME }}:${{ env.FAKE_IMAGE_TAG }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "${{ env.FAKE_DOCKER_USERNAME }}/${{ env.FAKE_IMAGE_NAME }}:${{ env.FAKE_IMAGE_TAG }}"
          # format: "table"
          # exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-results.sarif"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Snyk Container Test
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: "${{ env.FAKE_DOCKER_USERNAME }}/${{ env.FAKE_IMAGE_NAME }}:${{ env.FAKE_IMAGE_TAG }}"
          args: --file=Dockerfile --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Debug snyk.sarif
        run: cat snyk.sarif
      - name: Upload Snyk Container Test result to GitHub Code Scanning
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "snyk.sarif"
